platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def base_pods
    pod 'AFNetworking',                         '~> 3.0.0'
end

target 'Venus' do
    base_pods
end

target 'VenusStore' do
    base_pods
end

# Other configurations
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS'] = '$(ARCHS_STANDARD)'
            config.build_settings['VALID_ARCHS'] = 'armv7 armv7s arm64'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
