# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_PASSWORD"] = "BlooD1975"
ENV["MATCH_PASSWORD"] = "iOS123456"

default_platform(:ios)

platform :ios do
  lane :inHouse do
    setup_jenkins
    sync_code_signing(
      app_identifier: ["com.livesone.wallet"],
      keychain_password: "iOS123456",
      readonly: true,
      verbose: true,
      skip_docs: true,
      type: "enterprise",
      clone_branch_directly: true
    )
    build_number = increment_build_number
    gym(workspace: "Venus.xcworkspace",
      scheme: "Venus", 
      output_directory: "~/jenkins_builds/wallet/inhouse", 
      clean: true,
      include_bitcode: true,
      configuration: "AppStore",
      export_options: {
        method: "enterprise",
        provisioningProfiles: {"com.livesone.wallet" => "Wallet App Store"}
      })
    # Tag release and push to GitHub
    commit_version_bump(
      message: "Version Bump, build number bump to #{build_number}",# create a commit with a custom message
      xcodeproj: "Venus.xcodeproj",
      force: true
    )
    push_to_git_remote(
      remote: "origin",
      local_branch: "develop",
      remote_branch: "develop",
      tags: false,
      force: true
    )
  end
end
